Fix debug build on Android (#147)
Add missing `#include <string>`

LogMatrix.h:89:14: error: implicit instantiation of undefined template
'std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>,
 std::__ndk1::allocator<char>>'