Enable -Werror=return-type and fix compilation
The compiler doesn't know that the switch covers all cases
because technically any int can be stuffed into an enum value.

ReadBarcode.cpp:91:1: error: control reaches end of non-void function [-Werror=return-type]