Enable CXX_STANDARD 20 for all targets except for linux Kotlin/Native is bundled with gcc8 toolchain and sysroot for linux, and it seems that it doesn't support cxx20 fully.
Build log:
```
In file included from [...]/zxing-cpp/core/src/TextUtfEncoding.cpp:8:
[...]/zxing-cpp/core/src/Utf.h:16:28: error: no type named 'u8string_view' in namespace 'std'
std::wstring FromUtf8(std::u8string_view utf8);
                      ~~~~~^
1 error generated.
```