Silence deprecated-declarations warnings on Windows too
Seen when building zxing-cpp as an external library in LibreOffice
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\zxing\core\src\ReaderOptions.h(173): error C2220: the following warning is treated as an error
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\zxing\core\src\ReaderOptions.h(173): warning C4996: 'ZXing::ReaderOptions::tryCode39ExtendedMode': was declared deprecated
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\zxing\core\src\ReaderOptions.h(176): warning C4996: 'ZXing::ReaderOptions::validateCode39CheckSum': was declared deprecated
E:\jenkins\workspace\gerrit_windows_wsl\workdir\UnpackedTarball\zxing\core\src\ReaderOptions.h(180): warning C4996: 'ZXing::ReaderOptions::validateITFCheckSum': was declared deprecated